//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleClicker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleClicker.Properties.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This includes all window(s) related to this application..
        /// </summary>
        public static string alwaysOnTopHelpText {
            get {
                return ResourceManager.GetString("alwaysOnTopHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string alwaysOnTopText {
            get {
                return ResourceManager.GetString("alwaysOnTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribution.
        /// </summary>
        public static string attributionTabText {
            get {
                return ResourceManager.GetString("attributionTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string backButtonText {
            get {
                return ResourceManager.GetString("backButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the border color on top of the window..
        /// </summary>
        public static string borderColorHelpText {
            get {
                return ResourceManager.GetString("borderColorHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border color.
        /// </summary>
        public static string borderColorText {
            get {
                return ResourceManager.GetString("borderColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        public static string changeOptionText {
            get {
                return ResourceManager.GetString("changeOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes dark mode options. When set to &quot;System&quot;, this will changes theme depends on day / night..
        /// </summary>
        public static string darkModeHelpText {
            get {
                return ResourceManager.GetString("darkModeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string darkModeOption1 {
            get {
                return ResourceManager.GetString("darkModeOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string darkModeOption2 {
            get {
                return ResourceManager.GetString("darkModeOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string darkModeOption3 {
            get {
                return ResourceManager.GetString("darkModeOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string darkModeText {
            get {
                return ResourceManager.GetString("darkModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes color in delay phase..
        /// </summary>
        public static string delayColorHelpText {
            get {
                return ResourceManager.GetString("delayColorHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay time color.
        /// </summary>
        public static string delayTimeColorText {
            get {
                return ResourceManager.GetString("delayTimeColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On: Shows the remaining time on delay phase.
        ///Off: Doesn&apos;t show on delay phase..
        /// </summary>
        public static string delayTimeShowsHelpText {
            get {
                return ResourceManager.GetString("delayTimeShowsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show delay time.
        /// </summary>
        public static string delayTimeShowsText {
            get {
                return ResourceManager.GetString("delayTimeShowsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Time.
        /// </summary>
        public static string delayTimeText {
            get {
                return ResourceManager.GetString("delayTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string delayToText {
            get {
                return ResourceManager.GetString("delayToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Lapping.
        /// </summary>
        public static string enableLappingText {
            get {
                return ResourceManager.GetString("enableLappingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string extrasTabText {
            get {
                return ResourceManager.GetString("extrasTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timer will not record laps when limit is 0! Are you sure to continue? (Switch to -1 if you want unlimited laps).
        /// </summary>
        public static string infoNoLapRecord {
            get {
                return ResourceManager.GetString("infoNoLapRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset successfully. The application will now restart..
        /// </summary>
        public static string infoResetCompleted {
            get {
                return ResourceManager.GetString("infoResetCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string infoTabText {
            get {
                return ResourceManager.GetString("infoTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the signal....
        /// </summary>
        public static string infoWaitForSignal {
            get {
                return ResourceManager.GetString("infoWaitForSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string interfaceTabText {
            get {
                return ResourceManager.GetString("interfaceTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the language. Note that some may not
        ///be translated fully / correctly..
        /// </summary>
        public static string languageHelpText {
            get {
                return ResourceManager.GetString("languageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string languageText {
            get {
                return ResourceManager.GetString("languageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All durations (Default).
        /// </summary>
        public static string lapAllowanceOption0 {
            get {
                return ResourceManager.GetString("lapAllowanceOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After delays.
        /// </summary>
        public static string lapAllowanceOption1 {
            get {
                return ResourceManager.GetString("lapAllowanceOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delays only.
        /// </summary>
        public static string lapAllowanceOption2 {
            get {
                return ResourceManager.GetString("lapAllowanceOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow laps for.
        /// </summary>
        public static string lapAllowanceText {
            get {
                return ResourceManager.GetString("lapAllowanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap.
        /// </summary>
        public static string lapButtonText {
            get {
                return ResourceManager.GetString("lapButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How should the lap be displayed:
        ///  - Time per laps: A lap revolution
        ///  - Real-time: Clock time.
        /// </summary>
        public static string lapDisplayHelpText {
            get {
                return ResourceManager.GetString("lapDisplayHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time per laps.
        /// </summary>
        public static string lapDisplayTypeOption0 {
            get {
                return ResourceManager.GetString("lapDisplayTypeOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time (Default).
        /// </summary>
        public static string lapDisplayTypeOption1 {
            get {
                return ResourceManager.GetString("lapDisplayTypeOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display laps by.
        /// </summary>
        public static string lapDisplayTypeText {
            get {
                return ResourceManager.GetString("lapDisplayTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap.
        /// </summary>
        public static string lapIntervalText {
            get {
                return ResourceManager.GetString("lapIntervalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets how laps are recorded:
        ///  - All durations: All laps will be recorded.
        ///  - After delays: Only laps after delay is recorded.
        ///  - Delays only: Only laps in delay is recorded..
        /// </summary>
        public static string lapsAllowanceHelpText {
            get {
                return ResourceManager.GetString("lapsAllowanceHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizer.
        /// </summary>
        public static string lapSortingOption_1 {
            get {
                return ResourceManager.GetString("lapSortingOption_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First focused.
        /// </summary>
        public static string lapSortingOption0 {
            get {
                return ResourceManager.GetString("lapSortingOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last focused (Default).
        /// </summary>
        public static string lapSortingOption1 {
            get {
                return ResourceManager.GetString("lapSortingOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best to worst.
        /// </summary>
        public static string lapSortingOption2 {
            get {
                return ResourceManager.GetString("lapSortingOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst to best.
        /// </summary>
        public static string lapSortingOption3 {
            get {
                return ResourceManager.GetString("lapSortingOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort laps by.
        /// </summary>
        public static string lapSortingText {
            get {
                return ResourceManager.GetString("lapSortingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorts laps:
        ///  - First focused: First lap is focused.
        ///  - Last focused: Last lap is focused.
        ///  - Best to worst: Smallest to largest lap.
        ///  - Worst to last: Largest to smallest lap..
        /// </summary>
        public static string lapsSortingHelpText {
            get {
                return ResourceManager.GetString("lapsSortingHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laps.
        /// </summary>
        public static string lapsTabText {
            get {
                return ResourceManager.GetString("lapsTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string licenseTabText {
            get {
                return ResourceManager.GetString("licenseTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options....
        /// </summary>
        public static string moreOptionsButtonText {
            get {
                return ResourceManager.GetString("moreOptionsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options....
        /// </summary>
        public static string moreOptionsFormText {
            get {
                return ResourceManager.GetString("moreOptionsFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string optionsButtonText {
            get {
                return ResourceManager.GetString("optionsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes color in pause phase..
        /// </summary>
        public static string pauseColorHelpText {
            get {
                return ResourceManager.GetString("pauseColorHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause time color.
        /// </summary>
        public static string pauseTimeColorText {
            get {
                return ResourceManager.GetString("pauseTimeColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes color in preparation phase..
        /// </summary>
        public static string preparationColorHelpText {
            get {
                return ResourceManager.GetString("preparationColorHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation time color.
        /// </summary>
        public static string preparationTimeColorText {
            get {
                return ResourceManager.GetString("preparationTimeColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation Time.
        /// </summary>
        public static string preparationTimeText {
            get {
                return ResourceManager.GetString("preparationTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET ALL OPTIONS TO DEFAULT.
        /// </summary>
        public static string resetAllText {
            get {
                return ResourceManager.GetString("resetAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string resetButtonText {
            get {
                return ResourceManager.GetString("resetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset ex. options....
        /// </summary>
        public static string resetExtraText {
            get {
                return ResourceManager.GetString("resetExtraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset time options....
        /// </summary>
        public static string resetTimeText {
            get {
                return ResourceManager.GetString("resetTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute!.
        /// </summary>
        public static string secretButtonIdleText {
            get {
                return ResourceManager.GetString("secretButtonIdleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You found it!.
        /// </summary>
        public static string secretButtonSuccessText {
            get {
                return ResourceManager.GetString("secretButtonSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Only ONE secret could be applied at a time..
        /// </summary>
        public static string secretHelpText {
            get {
                return ResourceManager.GetString("secretHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter secret(s) below:.
        /// </summary>
        public static string secretText {
            get {
                return ResourceManager.GetString("secretText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string startButtonText {
            get {
                return ResourceManager.GetString("startButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes color in start phase..
        /// </summary>
        public static string startColorHelpText {
            get {
                return ResourceManager.GetString("startColorHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time color.
        /// </summary>
        public static string startTimeColorText {
            get {
                return ResourceManager.GetString("startTimeColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stopButtonText {
            get {
                return ResourceManager.GetString("stopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time to change theme to Off in &quot;Default&quot; dark mode option..
        /// </summary>
        public static string sunriseHelpText {
            get {
                return ResourceManager.GetString("sunriseHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise time.
        /// </summary>
        public static string sunriseText {
            get {
                return ResourceManager.GetString("sunriseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will changes theme to On in &quot;Default&quot; dark mode option..
        /// </summary>
        public static string sunsetHelpText {
            get {
                return ResourceManager.GetString("sunsetHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset time.
        /// </summary>
        public static string sunsetText {
            get {
                return ResourceManager.GetString("sunsetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string supportText {
            get {
                return ResourceManager.GetString("supportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        public static string systemInfoTabText {
            get {
                return ResourceManager.GetString("systemInfoTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string themeTabText {
            get {
                return ResourceManager.GetString("themeTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start..
        /// </summary>
        public static string tickIdleText {
            get {
                return ResourceManager.GetString("tickIdleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Precision.
        /// </summary>
        public static string timePrecisionText {
            get {
                return ResourceManager.GetString("timePrecisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to units.
        /// </summary>
        public static string timeUnitText {
            get {
                return ResourceManager.GetString("timeUnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Threshold.
        /// </summary>
        public static string updateThresholdText {
            get {
                return ResourceManager.GetString("updateThresholdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAIT.
        /// </summary>
        public static string waitButtonText {
            get {
                return ResourceManager.GetString("waitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timer is still running! Do you really want to exit?.
        /// </summary>
        public static string warningCloseWhenRunning {
            get {
                return ResourceManager.GetString("warningCloseWhenRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start timer when the options menu is opened!.
        /// </summary>
        public static string warningNoStartTimer {
            get {
                return ResourceManager.GetString("warningNoStartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARE YOU SURE TO RESET ALL SETTINGS? THIS ACTION IS IRREVERSIBLE!.
        /// </summary>
        public static string warningResetAllOptions {
            get {
                return ResourceManager.GetString("warningResetAllOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARE YOU SURE TO RESET EXTRA SETTINGS? THIS ACTION IS IRREVERSIBLE!.
        /// </summary>
        public static string warningResetExtraOptions {
            get {
                return ResourceManager.GetString("warningResetExtraOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARE YOU SURE TO RESET TIME SETTINGS? THIS ACTION IS IRREVERSIBLE!.
        /// </summary>
        public static string warningResetTimeOptions {
            get {
                return ResourceManager.GetString("warningResetTimeOptions", resourceCulture);
            }
        }
    }
}
